//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YandereSimulatorLauncher2.Properties.Lang {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YandereSimulatorLauncher2.Properties.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;lt;-- Report bugs affecting the launcher on the left..
        /// </summary>
        public static string affecting_left {
            get {
                return ResourceManager.GetString("affecting_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blog.
        /// </summary>
        public static string blog {
            get {
                return ResourceManager.GetString("blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If the bug affects the game, not the launcher, then submit the game bug to YandereDev through his website..
        /// </summary>
        public static string bug_affets {
            get {
                return ResourceManager.GetString("bug_affets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reporting Bugs.
        /// </summary>
        public static string bug_report {
            get {
                return ResourceManager.GetString("bug_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на submit launcher bugs to the above link..
        /// </summary>
        public static string bugs_to_the_link {
            get {
                return ResourceManager.GetString("bugs_to_the_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Busy Extracting Files.
        /// </summary>
        public static string busy_extracting {
            get {
                return ResourceManager.GetString("busy_extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot download game.
        /// </summary>
        public static string cannot_download_game {
            get {
                return ResourceManager.GetString("cannot_download_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot update Yandere Simulator.
        /// </summary>
        public static string cannot_update {
            get {
                return ResourceManager.GetString("cannot_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check out the status of reported bugs by looking at the project&apos;s issues tab on GitHub. If you have an account, you may also comment on issues, submit pull requests, and otherwise contribute to the launcher..
        /// </summary>
        public static string check_status {
            get {
                return ResourceManager.GetString("check_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check for updates.
        /// </summary>
        public static string check_updates {
            get {
                return ResourceManager.GetString("check_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirming....
        /// </summary>
        public static string confirming {
            get {
                return ResourceManager.GetString("confirming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do not.
        /// </summary>
        public static string do_not_submit_to_yandere1 {
            get {
                return ResourceManager.GetString("do_not_submit_to_yandere1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на submit launcher bug reports to YandereDev..
        /// </summary>
        public static string do_not_submit_to_yandere2 {
            get {
                return ResourceManager.GetString("do_not_submit_to_yandere2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Donate.
        /// </summary>
        public static string donate {
            get {
                return ResourceManager.GetString("donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error has occurred.\n\n Try again later or download directly from:\n https://yanderedev.wordpress.com/downloads.
        /// </summary>
        public static string download_eror {
            get {
                return ResourceManager.GetString("download_eror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading new launcher.
        /// </summary>
        public static string downloading_launcher {
            get {
                return ResourceManager.GetString("downloading_launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading....
        /// </summary>
        public static string downloading_text {
            get {
                return ResourceManager.GetString("downloading_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading Yandere Simulator:.
        /// </summary>
        public static string downloading_yandere {
            get {
                return ResourceManager.GetString("downloading_yandere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The project lead accepts bug reports by email at the following address:.
        /// </summary>
        public static string email_reports {
            get {
                return ResourceManager.GetString("email_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are attempting to run the launcher from within the ZIP.\n\nPlease extract YandereSimulatorLauncher2.exe from YandereSimLauncher.zip before running it..
        /// </summary>
        public static string extract_files {
            get {
                return ResourceManager.GetString("extract_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please extract YandereSimLauncher.zip.
        /// </summary>
        public static string extract_please_title {
            get {
                return ResourceManager.GetString("extract_please_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extracting files.
        /// </summary>
        public static string extracting_process {
            get {
                return ResourceManager.GetString("extracting_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found a bug?.
        /// </summary>
        public static string found_bug {
            get {
                return ResourceManager.GetString("found_bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bug in the launcher.
        /// </summary>
        public static string found_bug_launcher {
            get {
                return ResourceManager.GetString("found_bug_launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bug in the game.
        /// </summary>
        public static string game_bug {
            get {
                return ResourceManager.GetString("game_bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Install.
        /// </summary>
        public static string install_button {
            get {
                return ResourceManager.GetString("install_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yandere Simulator is running. Please shut down the game before performing the update..
        /// </summary>
        public static string is_running {
            get {
                return ResourceManager.GetString("is_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bug in the launcher.
        /// </summary>
        public static string launcher_bug {
            get {
                return ResourceManager.GetString("launcher_bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launching....
        /// </summary>
        public static string launching_test {
            get {
                return ResourceManager.GetString("launching_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yandere Simulator is not supported on this device..
        /// </summary>
        public static string notSupported {
            get {
                return ResourceManager.GetString("notSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Yandere Simulator launcher is an open-source project that is maintained by volunteers..
        /// </summary>
        public static string open_source {
            get {
                return ResourceManager.GetString("open_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play.
        /// </summary>
        public static string play_button {
            get {
                return ResourceManager.GetString("play_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retry install.
        /// </summary>
        public static string retry_install {
            get {
                return ResourceManager.GetString("retry_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The install button should be locked..
        /// </summary>
        public static string revelant_install_task {
            get {
                return ResourceManager.GetString("revelant_install_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yandere Simulator has failed to start.\nWould you like to fresh install the latest version?.
        /// </summary>
        public static string start_failed {
            get {
                return ResourceManager.GetString("start_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to launch Yandere Simulator.
        /// </summary>
        public static string start_failed_title {
            get {
                return ResourceManager.GetString("start_failed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Twitch.
        /// </summary>
        public static string twitch {
            get {
                return ResourceManager.GetString("twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Twitter.
        /// </summary>
        public static string twitter {
            get {
                return ResourceManager.GetString("twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to download the game. \n\n The launcher failed to login to Mega.nz&apos;s download service. \n\n Try to download the game (without the launcher) from one of the alternate links at: \n\n yanderedev.wordpress.com/downloads.
        /// </summary>
        public static string unable_to_download {
            get {
                return ResourceManager.GetString("unable_to_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The launcher encountered an unknown error. \n\n Please try again. If the problem persists, try going into the launcher folder and deleting YandereSimulator.zip and the YandereSimulator folder (if they exist). \n\n You can also download the game directly from one of the alternate links provided at: \n\n yanderedev.wordpress.com/downloads.
        /// </summary>
        public static string unknown_error {
            get {
                return ResourceManager.GetString("unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Closing the launcher while unpacking files will corrupt them.\n\nDo you wish to force-close the launcher anyway?.
        /// </summary>
        public static string unpack_error {
            get {
                return ResourceManager.GetString("unpack_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unpacking....
        /// </summary>
        public static string unpacking_text {
            get {
                return ResourceManager.GetString("unpacking_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update available.
        /// </summary>
        public static string update_aviabl {
            get {
                return ResourceManager.GetString("update_aviabl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launcher update available....
        /// </summary>
        public static string update_aviable {
            get {
                return ResourceManager.GetString("update_aviable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checking for updates....
        /// </summary>
        public static string update_check {
            get {
                return ResourceManager.GetString("update_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No update aviable.
        /// </summary>
        public static string updates_not_aviable {
            get {
                return ResourceManager.GetString("updates_not_aviable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video background.
        /// </summary>
        public static string video_background {
            get {
                return ResourceManager.GetString("video_background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volunteer.
        /// </summary>
        public static string volunteer {
            get {
                return ResourceManager.GetString("volunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waiting for something to do....
        /// </summary>
        public static string waiting_for_todo {
            get {
                return ResourceManager.GetString("waiting_for_todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The website did not provide a download link that the launcher could recognize. \n\n If the launcher is reporting that a new launcher version is available, then download it. Otherwise, report a launcher issue from the launcher..
        /// </summary>
        public static string website_not_provide {
            get {
                return ResourceManager.GetString("website_not_provide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows is telling the launcher that it is 32-bit.\n\nYandere Simulator requires 64-bit Windows.\n\nThis change happened on April 10th, 2020. .
        /// </summary>
        public static string x64Error {
            get {
                return ResourceManager.GetString("x64Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Youtube.
        /// </summary>
        public static string youtube {
            get {
                return ResourceManager.GetString("youtube", resourceCulture);
            }
        }
    }
}
